"""module12 statutory and compliance models

Revision ID: d541d1d4e434
Revises: ba40acc103c2
Create Date: 2026-09-27 01:43:44.297940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd541d1d4e434'
down_revision: Union[str, Sequence[str], None] = 'ba40acc103c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_assessments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('assessment_type', sa.Enum('ATTRITION_RISK', 'CANDIDATE_FIT', 'COMPENSATION_BENCHMARK', 'PERFORMANCE_ANOMALY', name='aiassessmenttype'), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('factors_json', sa.JSON(), nullable=True),
    sa.Column('recommendations_json', sa.JSON(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_assessments_entity_id'), 'ai_assessments', ['entity_id'], unique=False)
    op.create_index(op.f('ix_ai_assessments_entity_type'), 'ai_assessments', ['entity_type'], unique=False)
    op.create_table('ai_helpdesk_knowledge',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('keywords_json', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analytics_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('dimension', sa.String(), nullable=True),
    sa.Column('dimension_value', sa.String(), nullable=True),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analytics_snapshots_metric_name'), 'analytics_snapshots', ['metric_name'], unique=False)
    op.create_table('asset_catalog',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('asset_tag', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_cost', sa.String(), nullable=True),
    sa.Column('warranty_expiry', sa.Date(), nullable=True),
    sa.Column('vendor', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('AVAILABLE', 'ASSIGNED', 'MAINTENANCE', 'RETIRED', 'LOST', name='assetstatus'), nullable=False),
    sa.Column('condition', sa.Enum('NEW', 'GOOD', 'FAIR', 'POOR', 'DAMAGED', name='assetcondition'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'asset_tag', name='uq_asset_tenant_tag'),
    sa.UniqueConstraint('tenant_id', 'serial_number', name='uq_asset_tenant_serial')
    )
    op.create_index(op.f('ix_asset_catalog_tenant_id'), 'asset_catalog', ['tenant_id'], unique=False)
    op.create_table('compliance_policies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('CODE_OF_CONDUCT', 'INFO_SEC', 'ANTI_HARASSMENT', 'LEAVE_POLICY', 'COMPENSATION', 'REMOTE_WORK', name='policycategory'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('courses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('duration_hours', sa.Float(), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=True),
    sa.Column('instructor_name', sa.String(), nullable=True),
    sa.Column('max_enrollment', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='coursestatus'), nullable=True),
    sa.Column('modules_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('currency_rates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('from_currency', sa.String(), nullable=False),
    sa.Column('to_currency', sa.String(), nullable=False),
    sa.Column('exchange_rate', sa.Float(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('custom_field_definitions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('field_type', sa.Enum('TEXT', 'NUMBER', 'DATE', 'BOOLEAN', 'SELECT', 'MULTI_SELECT', name='customfieldtype'), nullable=False),
    sa.Column('options_json', sa.JSON(), nullable=True),
    sa.Column('is_required', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_field_definitions_entity_type'), 'custom_field_definitions', ['entity_type'], unique=False)
    op.create_table('holiday_calendars',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('country_code', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leave_policies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('leave_type', sa.String(), nullable=False),
    sa.Column('annual_quota', sa.Float(), nullable=False),
    sa.Column('accrual_frequency', sa.Enum('MONTHLY', 'QUARTERLY', 'YEARLY', 'NONE', name='accrualfrequency'), nullable=True),
    sa.Column('max_carry_forward', sa.Float(), nullable=True),
    sa.Column('max_consecutive_days', sa.Integer(), nullable=True),
    sa.Column('requires_attachment', sa.Boolean(), nullable=True),
    sa.Column('attachment_after_days', sa.Integer(), nullable=True),
    sa.Column('applicable_from', sa.Date(), nullable=True),
    sa.Column('applicable_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('notification_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('body_template', sa.Text(), nullable=False),
    sa.Column('channel', sa.Enum('IN_APP', 'EMAIL', 'SMS', 'PUSH', name='notificationchannel'), nullable=True),
    sa.Column('event_trigger', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('payroll_components',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('component_type', sa.Enum('EARNING', 'DEDUCTION', 'EMPLOYER_CONTRIBUTION', name='componenttype'), nullable=False),
    sa.Column('is_taxable', sa.Boolean(), nullable=True),
    sa.Column('is_statutory', sa.Boolean(), nullable=True),
    sa.Column('calculation_type', sa.String(), nullable=True),
    sa.Column('percentage_of', sa.String(), nullable=True),
    sa.Column('default_value', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('name')
    )
    op.create_table('persons',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('preferred_name', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('current_address', sa.Text(), nullable=True),
    sa.Column('permanent_address', sa.Text(), nullable=True),
    sa.Column('emergency_contact', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_persons_email'), 'persons', ['email'], unique=False)
    op.create_table('review_cycles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cycle_type', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('UPCOMING', 'ACTIVE', 'CLOSED', name='reviewcyclestatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('saml_providers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('sso_url', sa.String(), nullable=False),
    sa.Column('x509_cert', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entity_id')
    )
    op.create_table('security_policies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('min_password_length', sa.Integer(), nullable=False),
    sa.Column('require_uppercase', sa.Boolean(), nullable=False),
    sa.Column('require_numbers', sa.Boolean(), nullable=False),
    sa.Column('require_special_char', sa.Boolean(), nullable=False),
    sa.Column('session_timeout_minutes', sa.Integer(), nullable=False),
    sa.Column('max_failed_logins', sa.Integer(), nullable=False),
    sa.Column('ip_whitelist_enabled', sa.Boolean(), nullable=False),
    sa.Column('ip_whitelist_json', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('shift_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('shift_type', sa.Enum('GENERAL', 'MORNING', 'AFTERNOON', 'NIGHT', 'ROTATIONAL', 'FLEXIBLE', name='shifttype'), nullable=False),
    sa.Column('start_time', sa.String(), nullable=False),
    sa.Column('end_time', sa.String(), nullable=False),
    sa.Column('break_duration_minutes', sa.Integer(), nullable=True),
    sa.Column('is_night_shift', sa.Boolean(), nullable=True),
    sa.Column('min_rest_hours', sa.Integer(), nullable=True),
    sa.Column('color_code', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('tenants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('domain', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain')
    )
    op.create_table('workflow_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('workflow_type', sa.Enum('PROMOTION', 'SALARY_HIKE', 'EQUIPMENT_REQUEST', 'DOCUMENT_VERIFICATION', 'CUSTOM', name='workflowtype'), nullable=False),
    sa.Column('steps_definition', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('benefit_plans',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('benefit_type', sa.Enum('HEALTH_INSURANCE', 'LIFE_INSURANCE', 'RETIREMENT', 'WELLNESS', 'MEAL_BENEFIT', 'TRANSPORT', 'OTHER', name='benefittype'), nullable=False),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('employer_contribution', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('employee_deduction', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('coverage_details', sa.JSON(), nullable=True),
    sa.Column('eligibility_criteria', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_benefit_plans_tenant_id'), 'benefit_plans', ['tenant_id'], unique=False)
    op.create_table('custom_field_values',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('field_definition_id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('value_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['field_definition_id'], ['custom_field_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_field_values_entity_id'), 'custom_field_values', ['entity_id'], unique=False)
    op.create_index(op.f('ix_custom_field_values_entity_type'), 'custom_field_values', ['entity_type'], unique=False)
    op.create_table('enrollments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('course_id', sa.String(), nullable=False),
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ENROLLED', 'IN_PROGRESS', 'COMPLETED', 'DROPPED', name='enrollmentstatus'), nullable=True),
    sa.Column('progress_pct', sa.Float(), nullable=True),
    sa.Column('completed_modules', sa.JSON(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('enrolled_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrollments_person_id'), 'enrollments', ['person_id'], unique=False)
    op.create_table('holidays',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('calendar_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('holiday_type', sa.Enum('PUBLIC', 'REGIONAL', 'OPTIONAL', name='holidaytype'), nullable=False),
    sa.Column('is_mandatory', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['calendar_id'], ['holiday_calendars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leave_balances',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('leave_policy_id', sa.String(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('total_entitled', sa.Float(), nullable=False),
    sa.Column('used', sa.Float(), nullable=False),
    sa.Column('carry_forward', sa.Float(), nullable=False),
    sa.Column('remaining', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['leave_policy_id'], ['leave_policies.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_balances_person_id'), 'leave_balances', ['person_id'], unique=False)
    op.create_table('legal_entities',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('registration_number', sa.String(), nullable=True),
    sa.Column('tax_id', sa.String(), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('default_currency', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_legal_entities_tenant_id'), 'legal_entities', ['tenant_id'], unique=False)
    op.create_table('okr_objectives',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('review_cycle_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'COMPLETED', 'CANCELLED', name='objectivestatus'), nullable=True),
    sa.Column('progress_pct', sa.Float(), nullable=True),
    sa.Column('parent_objective_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_objective_id'], ['okr_objectives.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['review_cycle_id'], ['review_cycles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_okr_objectives_person_id'), 'okr_objectives', ['person_id'], unique=False)
    op.create_table('salary_structures',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('ctc_annual', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('ctc_monthly', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('components_json', sa.JSON(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salary_structures_person_id'), 'salary_structures', ['person_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'HR_ADMIN', 'HIRING_MANAGER', 'EMPLOYEE', 'FINANCE', name='userrole'), nullable=False),
    sa.Column('person_id', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('active_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('session_token_hash', sa.String(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_active_sessions_session_token_hash'), 'active_sessions', ['session_token_hash'], unique=False)
    op.create_index(op.f('ix_active_sessions_user_id'), 'active_sessions', ['user_id'], unique=False)
    op.create_table('announcements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='notificationpriority'), nullable=True),
    sa.Column('target_audience', sa.String(), nullable=True),
    sa.Column('is_pinned', sa.Boolean(), nullable=True),
    sa.Column('published_by_id', sa.String(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['published_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset_assignment_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('employee_person_id', sa.String(), nullable=True),
    sa.Column('employee_user_id', sa.String(), nullable=True),
    sa.Column('action', sa.Enum('ASSIGN', 'TRANSFER', 'RETURN', name='assetassignmentaction'), nullable=False),
    sa.Column('from_status', sa.Enum('AVAILABLE', 'ASSIGNED', 'MAINTENANCE', 'RETIRED', 'LOST', name='assetstatus'), nullable=True),
    sa.Column('to_status', sa.Enum('AVAILABLE', 'ASSIGNED', 'MAINTENANCE', 'RETIRED', 'LOST', name='assetstatus'), nullable=False),
    sa.Column('performed_at', sa.DateTime(), nullable=False),
    sa.Column('performed_by_user_id', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('previous_employee_person_id', sa.String(), nullable=True),
    sa.Column('new_employee_person_id', sa.String(), nullable=True),
    sa.Column('previous_location', sa.String(), nullable=True),
    sa.Column('new_location', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['asset_catalog.id'], ),
    sa.ForeignKeyConstraint(['employee_person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['employee_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['performed_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'action', 'performed_at', name='uq_asset_action_timestamp')
    )
    op.create_index(op.f('ix_asset_assignment_history_asset_id'), 'asset_assignment_history', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_assignment_history_employee_person_id'), 'asset_assignment_history', ['employee_person_id'], unique=False)
    op.create_index(op.f('ix_asset_assignment_history_employee_user_id'), 'asset_assignment_history', ['employee_user_id'], unique=False)
    op.create_index(op.f('ix_asset_assignment_history_tenant_id'), 'asset_assignment_history', ['tenant_id'], unique=False)
    op.create_table('attendance',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'HALF_DAY', 'ON_LEAVE', 'HOLIDAY', name='attendancestatus'), nullable=False),
    sa.Column('check_in', sa.DateTime(), nullable=True),
    sa.Column('check_out', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_person_id'), 'attendance', ['person_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('result', sa.Enum('SUCCESS', 'FAILURE', 'DENIED', name='auditresult'), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('benefit_enrollments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('benefit_plan_id', sa.String(), nullable=False),
    sa.Column('coverage_tier', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('ENROLLED', 'PENDING', 'TERMINATED', 'WAIVED', name='enrollmentstatus'), nullable=False),
    sa.Column('employee_contribution', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('employer_contribution', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('enrolled_by_id', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['benefit_plan_id'], ['benefit_plans.id'], ),
    sa.ForeignKeyConstraint(['enrolled_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_benefit_enrollments_person_id'), 'benefit_enrollments', ['person_id'], unique=False)
    op.create_index(op.f('ix_benefit_enrollments_tenant_id'), 'benefit_enrollments', ['tenant_id'], unique=False)
    op.create_table('bonus_incentives',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('bonus_type', sa.Enum('PERFORMANCE', 'RETENTION', 'SALES_INCENTIVE', 'SPOT_AWARD', 'ANNUAL', 'SIGNING', name='bonustype'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('pay_period', sa.String(length=7), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'APPROVED', 'REJECTED', name='bonusstatus'), nullable=False),
    sa.Column('payroll_status', sa.String(length=20), nullable=False),
    sa.Column('created_by_id', sa.String(), nullable=False),
    sa.Column('approved_by_id', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bonus_incentives_person_id'), 'bonus_incentives', ['person_id'], unique=False)
    op.create_index(op.f('ix_bonus_incentives_tenant_id'), 'bonus_incentives', ['tenant_id'], unique=False)
    op.create_table('comp_off_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('worked_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('comp_off_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED', name='compoffstatus'), nullable=False),
    sa.Column('approved_by_id', sa.String(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comp_off_requests_person_id'), 'comp_off_requests', ['person_id'], unique=False)
    op.create_table('compensation_revisions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('previous_salary_structure_id', sa.String(), nullable=True),
    sa.Column('previous_ctc_annual', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('new_ctc_annual', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('new_ctc_monthly', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('components_json', sa.JSON(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Enum('ANNUAL_REVIEW', 'PROMOTION', 'MARKET_ADJUSTMENT', 'RETENTION', 'PROBATION_CONFIRMATION', 'AD_HOC', name='revisionreason'), nullable=False),
    sa.Column('business_justification', sa.Text(), nullable=True),
    sa.Column('hr_notes', sa.Text(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'EFFECTIVE', name='revisionstatus'), nullable=False),
    sa.Column('created_by_id', sa.String(), nullable=False),
    sa.Column('recommended_by_id', sa.String(), nullable=True),
    sa.Column('approved_by_id', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('resulting_salary_structure_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['previous_salary_structure_id'], ['salary_structures.id'], ),
    sa.ForeignKeyConstraint(['recommended_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['resulting_salary_structure_id'], ['salary_structures.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compensation_revisions_person_id'), 'compensation_revisions', ['person_id'], unique=False)
    op.create_index(op.f('ix_compensation_revisions_tenant_id'), 'compensation_revisions', ['tenant_id'], unique=False)
    op.create_table('cost_centers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('legal_entity_id', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['legal_entity_id'], ['legal_entities.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_centers_tenant_id'), 'cost_centers', ['tenant_id'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('legal_entity_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parent_department_id', sa.String(), nullable=True),
    sa.Column('manager_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['legal_entity_id'], ['legal_entities.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['parent_department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_tenant_id'), 'departments', ['tenant_id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('document_type', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=False),
    sa.Column('storage_key', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'UPLOADED', 'UNDER_REVIEW', 'VERIFIED', 'REJECTED', name='documentstatus'), nullable=False),
    sa.Column('uploaded_by_id', sa.String(), nullable=True),
    sa.Column('upload_date', sa.DateTime(), nullable=True),
    sa.Column('verified_by_id', sa.String(), nullable=True),
    sa.Column('verification_date', sa.DateTime(), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verified_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee_assets',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('catalog_id', sa.String(), nullable=True),
    sa.Column('asset_name', sa.String(), nullable=False),
    sa.Column('asset_type', sa.String(), nullable=False),
    sa.Column('serial_number', sa.String(), nullable=True),
    sa.Column('assigned_date', sa.Date(), nullable=False),
    sa.Column('return_status', sa.String(), nullable=False),
    sa.Column('condition_at_assignment', sa.Enum('NEW', 'GOOD', 'FAIR', 'POOR', 'DAMAGED', name='assetcondition'), nullable=True),
    sa.Column('condition_at_return', sa.Enum('NEW', 'GOOD', 'FAIR', 'POOR', 'DAMAGED', name='assetcondition'), nullable=True),
    sa.Column('expected_return_date', sa.Date(), nullable=True),
    sa.Column('returned_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['catalog_id'], ['asset_catalog.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_assets_catalog_id'), 'employee_assets', ['catalog_id'], unique=False)
    op.create_index(op.f('ix_employee_assets_person_id'), 'employee_assets', ['person_id'], unique=False)
    op.create_index(op.f('ix_employee_assets_tenant_id'), 'employee_assets', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_employee_assets_user_id'), 'employee_assets', ['user_id'], unique=False)
    op.create_table('employee_relations_cases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('case_number', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('CONDUCT', 'ATTENDANCE', 'PERFORMANCE', 'WORKPLACE_BEHAVIOR', 'POLICY_VIOLATION', 'DISCIPLINARY', 'OTHER', name='ercasecategory'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='ercaseseverity'), nullable=False),
    sa.Column('subject_person_id', sa.String(), nullable=False),
    sa.Column('reporting_manager_id', sa.String(), nullable=True),
    sa.Column('hr_owner_id', sa.String(), nullable=False),
    sa.Column('created_by_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'UNDER_REVIEW', 'INVESTIGATION', 'ACTION_REQUIRED', 'RESOLVED', 'CLOSED', name='ercasestatus'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('investigation_summary', sa.Text(), nullable=True),
    sa.Column('resolution_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['hr_owner_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reporting_manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['subject_person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_relations_cases_case_number'), 'employee_relations_cases', ['case_number'], unique=True)
    op.create_index(op.f('ix_employee_relations_cases_subject_person_id'), 'employee_relations_cases', ['subject_person_id'], unique=False)
    op.create_index(op.f('ix_employee_relations_cases_tenant_id'), 'employee_relations_cases', ['tenant_id'], unique=False)
    op.create_table('exit_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ticket_number', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('resignation_date', sa.Date(), nullable=False),
    sa.Column('proposed_last_working_day', sa.Date(), nullable=False),
    sa.Column('approved_last_working_day', sa.Date(), nullable=True),
    sa.Column('notice_period_days', sa.Integer(), nullable=False),
    sa.Column('reason_category', sa.String(), nullable=True),
    sa.Column('employee_comments', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'NOTICE_PERIOD', 'CLEARANCE', 'EXIT_INTERVIEW', 'SETTLEMENT_PENDING', 'COMPLETED', 'CANCELLED', name='exitstatus'), nullable=False),
    sa.Column('manager_comments', sa.Text(), nullable=True),
    sa.Column('hr_comments', sa.Text(), nullable=True),
    sa.Column('manager_reviewed_by_id', sa.String(), nullable=True),
    sa.Column('manager_approved_at', sa.DateTime(), nullable=True),
    sa.Column('hr_reviewed_by_id', sa.String(), nullable=True),
    sa.Column('hr_approved_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hr_reviewed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['manager_reviewed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exit_requests_person_id'), 'exit_requests', ['person_id'], unique=False)
    op.create_index(op.f('ix_exit_requests_status'), 'exit_requests', ['status'], unique=False)
    op.create_index(op.f('ix_exit_requests_tenant_id'), 'exit_requests', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_exit_requests_ticket_number'), 'exit_requests', ['ticket_number'], unique=True)
    op.create_index(op.f('ix_exit_requests_user_id'), 'exit_requests', ['user_id'], unique=False)
    op.create_table('expense_claims',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ticket_number', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('merchant', sa.String(), nullable=True),
    sa.Column('receipt_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_claims_person_id'), 'expense_claims', ['person_id'], unique=False)
    op.create_index(op.f('ix_expense_claims_tenant_id'), 'expense_claims', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_expense_claims_ticket_number'), 'expense_claims', ['ticket_number'], unique=True)
    op.create_index(op.f('ix_expense_claims_user_id'), 'expense_claims', ['user_id'], unique=False)
    op.create_table('grievance_cases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ticket_number', sa.String(), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), nullable=True),
    sa.Column('complainant_user_id', sa.String(), nullable=True),
    sa.Column('category', sa.Enum('HARASSMENT', 'DISCRIMINATION', 'COMPENSATION_DISPUTE', 'SAFETY_HEALTH', 'ETHICS_VIOLATION', 'GENERAL', name='grievancecategory'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'UNDER_REVIEW', 'INVESTIGATING', 'RESOLVED', 'DISMISSED', name='grievancestatus'), nullable=False),
    sa.Column('assigned_investigator_id', sa.String(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_investigator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['complainant_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ticket_number')
    )
    op.create_table('hr_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ticket_number', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('requester_user_id', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('PAYROLL', 'LEAVE', 'ATTENDANCE', 'BENEFITS', 'DOCUMENTS', 'EMPLOYMENT_VERIFICATION', 'ONBOARDING', 'OFFBOARDING', 'IT_ACCESS', 'POLICY', 'GENERAL_HR', name='hrrequestcategory'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='hrrequestpriority'), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ASSIGNED', 'IN_PROGRESS', 'WAITING_FOR_EMPLOYEE', 'RESOLVED', 'CLOSED', name='hrrequeststatus'), nullable=False),
    sa.Column('assigned_to_user_id', sa.String(), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.Column('sla_due_date', sa.Date(), nullable=True),
    sa.Column('first_response_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requester_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_requests_requester_user_id'), 'hr_requests', ['requester_user_id'], unique=False)
    op.create_index(op.f('ix_hr_requests_status'), 'hr_requests', ['status'], unique=False)
    op.create_index(op.f('ix_hr_requests_tenant_id'), 'hr_requests', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_hr_requests_ticket_number'), 'hr_requests', ['ticket_number'], unique=True)
    op.create_table('job_openings',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('employment_type', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('required_skills', sa.JSON(), nullable=True),
    sa.Column('min_experience_years', sa.Integer(), nullable=True),
    sa.Column('salary_range_min', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_range_max', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'OPEN', 'ON_HOLD', 'CLOSED', name='jobstatus'), nullable=False),
    sa.Column('created_by_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leave_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('leave_type', sa.Enum('CASUAL', 'SICK', 'EARNED', 'UNPAID', 'MATERNITY', 'PATERNITY', 'OTHER', name='leavetype'), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('days', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='leavestatus'), nullable=False),
    sa.Column('reviewed_by_id', sa.String(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_requests_person_id'), 'leave_requests', ['person_id'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('legal_entity_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address_line1', sa.String(), nullable=True),
    sa.Column('address_line2', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('timezone', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['legal_entity_id'], ['legal_entities.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_tenant_id'), 'locations', ['tenant_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('channel', sa.Enum('IN_APP', 'EMAIL', 'SMS', 'PUSH', name='notificationchannel'), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='notificationpriority'), nullable=True),
    sa.Column('status', sa.Enum('UNREAD', 'READ', 'ARCHIVED', name='notificationstatus'), nullable=True),
    sa.Column('action_url', sa.String(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['notification_templates.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('okr_key_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('objective_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('target_value', sa.Float(), nullable=False),
    sa.Column('current_value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'COMPLETED', name='krstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['objective_id'], ['okr_objectives.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payroll_runs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('month', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PROCESSING', 'COMPUTED', 'APPROVED', 'DISBURSED', 'REVERSED', name='payrollrunstatus'), nullable=False),
    sa.Column('total_gross', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_deductions', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_net', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('employee_count', sa.Integer(), nullable=True),
    sa.Column('processed_by_id', sa.String(), nullable=True),
    sa.Column('approved_by_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['processed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('performance_reviews',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('review_cycle_id', sa.String(), nullable=False),
    sa.Column('reviewer_id', sa.String(), nullable=False),
    sa.Column('self_rating', sa.Enum('EXCEEDS', 'MEETS', 'BELOW', 'NEEDS_IMPROVEMENT', name='reviewrating'), nullable=True),
    sa.Column('manager_rating', sa.Enum('EXCEEDS', 'MEETS', 'BELOW', 'NEEDS_IMPROVEMENT', name='reviewrating'), nullable=True),
    sa.Column('final_rating', sa.Enum('EXCEEDS', 'MEETS', 'BELOW', 'NEEDS_IMPROVEMENT', name='reviewrating'), nullable=True),
    sa.Column('self_comments', sa.Text(), nullable=True),
    sa.Column('manager_comments', sa.Text(), nullable=True),
    sa.Column('goals_met_pct', sa.Float(), nullable=True),
    sa.Column('is_submitted', sa.Boolean(), nullable=True),
    sa.Column('is_acknowledged', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['review_cycle_id'], ['review_cycles.id'], ),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_reviews_person_id'), 'performance_reviews', ['person_id'], unique=False)
    op.create_table('policy_acknowledgments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('policy_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['compliance_policies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_acknowledgments_user_id'), 'policy_acknowledgments', ['user_id'], unique=False)
    op.create_table('shift_assignments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('shift_template_id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('actual_start', sa.DateTime(), nullable=True),
    sa.Column('actual_end', sa.DateTime(), nullable=True),
    sa.Column('is_overtime', sa.Boolean(), nullable=True),
    sa.Column('overtime_hours', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['shift_template_id'], ['shift_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shift_assignments_person_id'), 'shift_assignments', ['person_id'], unique=False)
    op.create_table('training_certificates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('enrollment_id', sa.String(), nullable=False),
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('certificate_number', sa.String(), nullable=False),
    sa.Column('issued_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('certificate_number')
    )
    op.create_table('workflow_instances',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=False),
    sa.Column('requester_id', sa.String(), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='workflowstatus'), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('approval_history', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['workflow_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('applied_position', sa.String(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('recruiter', sa.String(), nullable=True),
    sa.Column('hiring_manager_id', sa.String(), nullable=True),
    sa.Column('application_date', sa.Date(), nullable=True),
    sa.Column('interview_status', sa.String(), nullable=True),
    sa.Column('interview_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('APPLIED', 'SCREENING', 'INTERVIEW', 'SELECTED', 'REJECTED', 'ON_HOLD', 'CONVERTED_TO_TRAINEE', 'CONVERTED_TO_EMPLOYEE', name='candidatestatus'), nullable=False),
    sa.Column('resume_document_id', sa.String(), nullable=True),
    sa.Column('highest_qualification', sa.String(), nullable=True),
    sa.Column('college_university', sa.String(), nullable=True),
    sa.Column('linkedin_url', sa.String(), nullable=True),
    sa.Column('github_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['hiring_manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['resume_document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('person_id')
    )
    op.create_table('disciplinary_actions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('case_id', sa.String(), nullable=True),
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('action_type', sa.Enum('VERBAL_WARNING', 'WRITTEN_WARNING', 'FINAL_WARNING', 'PIP', 'SUSPENSION', 'OTHER', name='disciplinaryactiontype'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('action_plan', sa.Text(), nullable=True),
    sa.Column('issued_by_id', sa.String(), nullable=False),
    sa.Column('issued_date', sa.Date(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'REVOKED', 'EXPIRED', name='disciplinarystatus'), nullable=False),
    sa.Column('employee_acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['employee_relations_cases.id'], ),
    sa.ForeignKeyConstraint(['issued_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_disciplinary_actions_case_id'), 'disciplinary_actions', ['case_id'], unique=False)
    op.create_index(op.f('ix_disciplinary_actions_person_id'), 'disciplinary_actions', ['person_id'], unique=False)
    op.create_index(op.f('ix_disciplinary_actions_tenant_id'), 'disciplinary_actions', ['tenant_id'], unique=False)
    op.create_table('employment_history',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('change_type', sa.Enum('JOINING', 'PROMOTION', 'TRANSFER', 'COMPENSATION_REVISION', 'MANAGER_CHANGE', 'STATUS_CHANGE', 'EXIT', name='historychangetype'), nullable=False),
    sa.Column('designation', sa.String(), nullable=True),
    sa.Column('department_id', sa.String(), nullable=True),
    sa.Column('location_id', sa.String(), nullable=True),
    sa.Column('manager_id', sa.String(), nullable=True),
    sa.Column('legal_entity_id', sa.String(), nullable=True),
    sa.Column('salary_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('salary_currency', sa.String(length=3), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['legal_entity_id'], ['legal_entities.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employment_history_person_id'), 'employment_history', ['person_id'], unique=False)
    op.create_index(op.f('ix_employment_history_tenant_id'), 'employment_history', ['tenant_id'], unique=False)
    op.create_table('er_case_notes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('case_id', sa.String(), nullable=False),
    sa.Column('author_id', sa.String(), nullable=False),
    sa.Column('note_type', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_confidential', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['employee_relations_cases.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_er_case_notes_case_id'), 'er_case_notes', ['case_id'], unique=False)
    op.create_index(op.f('ix_er_case_notes_tenant_id'), 'er_case_notes', ['tenant_id'], unique=False)
    op.create_table('exit_clearance_tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('exit_request_id', sa.String(), nullable=False),
    sa.Column('department', sa.Enum('MANAGER', 'HR', 'FINANCE', 'IT', 'ASSETS', 'ADMIN', name='exitclearancedepartment'), nullable=False),
    sa.Column('task_name', sa.String(), nullable=False),
    sa.Column('is_cleared', sa.Boolean(), nullable=False),
    sa.Column('cleared_by_user_id', sa.String(), nullable=True),
    sa.Column('cleared_at', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cleared_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['exit_request_id'], ['exit_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exit_clearance_tasks_exit_request_id'), 'exit_clearance_tasks', ['exit_request_id'], unique=False)
    op.create_table('exit_handovers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('exit_request_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('recipient_user_id', sa.String(), nullable=True),
    sa.Column('recipient_name', sa.String(), nullable=True),
    sa.Column('documentation_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exit_request_id'], ['exit_requests.id'], ),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exit_handovers_exit_request_id'), 'exit_handovers', ['exit_request_id'], unique=False)
    op.create_table('exit_interviews',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('exit_request_id', sa.String(), nullable=False),
    sa.Column('interview_date', sa.Date(), nullable=True),
    sa.Column('interviewer_user_id', sa.String(), nullable=True),
    sa.Column('primary_reason', sa.String(), nullable=True),
    sa.Column('feedback_company', sa.Text(), nullable=True),
    sa.Column('feedback_management', sa.Text(), nullable=True),
    sa.Column('feedback_role', sa.Text(), nullable=True),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exit_request_id'], ['exit_requests.id'], ),
    sa.ForeignKeyConstraint(['interviewer_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exit_interviews_exit_request_id'), 'exit_interviews', ['exit_request_id'], unique=False)
    op.create_table('exit_settlements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('exit_request_id', sa.String(), nullable=False),
    sa.Column('payroll_reviewed', sa.Boolean(), nullable=False),
    sa.Column('leave_balance_reviewed', sa.Boolean(), nullable=False),
    sa.Column('leave_encashment_days', sa.Float(), nullable=False),
    sa.Column('asset_clearance_completed', sa.Boolean(), nullable=False),
    sa.Column('finance_clearance_completed', sa.Boolean(), nullable=False),
    sa.Column('settlement_status', sa.String(), nullable=False),
    sa.Column('settlement_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('settled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exit_request_id'], ['exit_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exit_settlements_exit_request_id'), 'exit_settlements', ['exit_request_id'], unique=False)
    op.create_table('hr_policies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('policy_code', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('CODE_OF_CONDUCT', 'LEAVE_ATTENDANCE', 'IT_SECURITY', 'REMOTE_WORK', 'COMPENSATION_BENEFITS', 'WORKPLACE_SAFETY', 'DISCIPLINARY', 'EQUAL_OPPORTUNITY', 'GENERAL', name='hrpolicycategory'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'REVIEW', 'APPROVED', 'PUBLISHED', 'ARCHIVED', name='hrpolicystatus'), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=True),
    sa.Column('legal_entity_id', sa.String(), nullable=True),
    sa.Column('department_id', sa.String(), nullable=True),
    sa.Column('employment_type', sa.String(), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=False),
    sa.Column('previous_version_id', sa.String(), nullable=True),
    sa.Column('created_by_id', sa.String(), nullable=False),
    sa.Column('approved_by_id', sa.String(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('published_by_id', sa.String(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['legal_entity_id'], ['legal_entities.id'], ),
    sa.ForeignKeyConstraint(['previous_version_id'], ['hr_policies.id'], ),
    sa.ForeignKeyConstraint(['published_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_policies_policy_code'), 'hr_policies', ['policy_code'], unique=False)
    op.create_index(op.f('ix_hr_policies_tenant_id'), 'hr_policies', ['tenant_id'], unique=False)
    op.create_table('hr_request_comments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hr_request_id', sa.String(), nullable=False),
    sa.Column('author_user_id', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['hr_request_id'], ['hr_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hr_request_comments_hr_request_id'), 'hr_request_comments', ['hr_request_id'], unique=False)
    op.create_table('onboarding_templates',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('department_id', sa.String(), nullable=True),
    sa.Column('checklist_tasks_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_templates_tenant_id'), 'onboarding_templates', ['tenant_id'], unique=False)
    op.create_table('payslips',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('payroll_run_id', sa.String(), nullable=False),
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('month', sa.String(), nullable=False),
    sa.Column('gross_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_deductions', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('net_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('earnings_json', sa.JSON(), nullable=True),
    sa.Column('deductions_json', sa.JSON(), nullable=True),
    sa.Column('working_days', sa.Integer(), nullable=True),
    sa.Column('days_paid', sa.Integer(), nullable=True),
    sa.Column('lop_days', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['payroll_runs.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payslips_person_id'), 'payslips', ['person_id'], unique=False)
    op.create_table('shift_swap_requests',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('requester_assignment_id', sa.String(), nullable=False),
    sa.Column('target_assignment_id', sa.String(), nullable=False),
    sa.Column('requester_id', sa.String(), nullable=False),
    sa.Column('target_user_id', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', name='swapstatus'), nullable=False),
    sa.Column('reviewed_by_id', sa.String(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['requester_assignment_id'], ['shift_assignments.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_assignment_id'], ['shift_assignments.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate_applications',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('candidate_id', sa.String(), nullable=False),
    sa.Column('stage', sa.Enum('APPLIED', 'SCREENING', 'INTERVIEW', 'OFFER_SENT', 'HIRED', 'REJECTED', name='applicationstage'), nullable=False),
    sa.Column('ai_match_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ai_match_reasons', sa.JSON(), nullable=True),
    sa.Column('parsed_skills', sa.JSON(), nullable=True),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('offer_letter_document_id', sa.String(), nullable=True),
    sa.Column('applied_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['job_openings.id'], ),
    sa.ForeignKeyConstraint(['offer_letter_document_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('engagements',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('converted_from_candidate_id', sa.String(), nullable=True),
    sa.Column('engagement_type', sa.Enum('INTERN', 'ENGINEERING_TRAINEE', 'GRADUATE_TRAINEE', 'PROBATIONARY_EMPLOYEE', 'FULL_TIME_EMPLOYEE', 'CONTRACTOR', 'CONSULTANT', name='engagementtype'), nullable=False),
    sa.Column('designation', sa.String(), nullable=False),
    sa.Column('department', sa.String(), nullable=False),
    sa.Column('reporting_manager_id', sa.String(), nullable=True),
    sa.Column('work_location', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('stipend_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('stipend_currency', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING_JOINING', 'ACTIVE', 'ON_LEAVE', 'NOTICE_PERIOD', 'COMPLETED', 'TERMINATED', 'RESIGNED', 'ARCHIVED', name='engagementstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['converted_from_candidate_id'], ['candidates.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['reporting_manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('onboarding_processes',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('template_id', sa.String(), nullable=True),
    sa.Column('target_joining_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('PREBOARDING', 'ONBOARDING', 'COMPLETED', 'CANCELLED', name='onboardingstatus'), nullable=False),
    sa.Column('completion_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['onboarding_templates.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_processes_person_id'), 'onboarding_processes', ['person_id'], unique=False)
    op.create_index(op.f('ix_onboarding_processes_tenant_id'), 'onboarding_processes', ['tenant_id'], unique=False)
    op.create_table('policy_acknowledgement_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=True),
    sa.Column('policy_id', sa.String(), nullable=False),
    sa.Column('policy_version', sa.String(), nullable=False),
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.ForeignKeyConstraint(['policy_id'], ['hr_policies.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policy_acknowledgement_records_person_id'), 'policy_acknowledgement_records', ['person_id'], unique=False)
    op.create_index(op.f('ix_policy_acknowledgement_records_policy_id'), 'policy_acknowledgement_records', ['policy_id'], unique=False)
    op.create_index(op.f('ix_policy_acknowledgement_records_tenant_id'), 'policy_acknowledgement_records', ['tenant_id'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('engagement_id', sa.String(), nullable=True),
    sa.Column('evaluator_id', sa.String(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('overall_rating', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'ACKNOWLEDGED', name='evaluationstatus'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.ForeignKeyConstraint(['evaluator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluations_person_id'), 'evaluations', ['person_id'], unique=False)
    op.create_table('interview_schedules',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('application_id', sa.String(), nullable=False),
    sa.Column('interviewer_id', sa.String(), nullable=False),
    sa.Column('interview_type', sa.Enum('PHONE_SCREEN', 'VIDEO', 'ONSITE', 'PANEL', 'TECHNICAL', 'HR', 'CULTURE_FIT', name='interviewtype'), nullable=False),
    sa.Column('scheduled_start', sa.DateTime(), nullable=False),
    sa.Column('scheduled_end', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('meeting_link', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='interviewstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['candidate_applications.id'], ),
    sa.ForeignKeyConstraint(['interviewer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offer_letters',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('application_id', sa.String(), nullable=False),
    sa.Column('offered_designation', sa.String(), nullable=False),
    sa.Column('offered_department', sa.String(), nullable=False),
    sa.Column('offered_salary', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('offered_currency', sa.String(), nullable=False),
    sa.Column('joining_date', sa.Date(), nullable=True),
    sa.Column('offer_expiry_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_APPROVAL', 'APPROVED', 'SENT', 'ACCEPTED', 'DECLINED', 'WITHDRAWN', 'EXPIRED', name='offerstatus'), nullable=False),
    sa.Column('approved_by_id', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['candidate_applications.id'], ),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('onboarding_tasks',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('process_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('category', sa.Enum('DOCUMENT', 'EQUIPMENT', 'TRAINING', 'ACCOUNT_PROVISIONING', 'MANAGER_INTRO', name='taskcategory'), nullable=False),
    sa.Column('assignee_role', sa.Enum('EMPLOYEE', 'HR', 'IT', 'MANAGER', name='taskassigneerole'), nullable=False),
    sa.Column('assigned_user_id', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'SKIPPED', name='taskstatus'), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['process_id'], ['onboarding_processes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_tasks_process_id'), 'onboarding_tasks', ['process_id'], unique=False)
    op.create_table('stipends',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('person_id', sa.String(), nullable=False),
    sa.Column('engagement_id', sa.String(), nullable=True),
    sa.Column('month', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'PAID', 'CANCELLED', name='stipendstatus'), nullable=False),
    sa.Column('approved_by_id', sa.String(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['engagement_id'], ['engagements.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stipends_person_id'), 'stipends', ['person_id'], unique=False)
    op.create_table('interview_scorecards',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('interview_id', sa.String(), nullable=False),
    sa.Column('evaluator_id', sa.String(), nullable=False),
    sa.Column('technical_score', sa.Integer(), nullable=True),
    sa.Column('communication_score', sa.Integer(), nullable=True),
    sa.Column('culture_fit_score', sa.Integer(), nullable=True),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('verdict', sa.Enum('STRONG_YES', 'YES', 'NEUTRAL', 'NO', 'STRONG_NO', name='scorecardverdict'), nullable=False),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('weaknesses', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['evaluator_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['interview_id'], ['interview_schedules.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interview_scorecards')
    op.drop_index(op.f('ix_stipends_person_id'), table_name='stipends')
    op.drop_table('stipends')
    op.drop_index(op.f('ix_onboarding_tasks_process_id'), table_name='onboarding_tasks')
    op.drop_table('onboarding_tasks')
    op.drop_table('offer_letters')
    op.drop_table('interview_schedules')
    op.drop_index(op.f('ix_evaluations_person_id'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_policy_acknowledgement_records_tenant_id'), table_name='policy_acknowledgement_records')
    op.drop_index(op.f('ix_policy_acknowledgement_records_policy_id'), table_name='policy_acknowledgement_records')
    op.drop_index(op.f('ix_policy_acknowledgement_records_person_id'), table_name='policy_acknowledgement_records')
    op.drop_table('policy_acknowledgement_records')
    op.drop_index(op.f('ix_onboarding_processes_tenant_id'), table_name='onboarding_processes')
    op.drop_index(op.f('ix_onboarding_processes_person_id'), table_name='onboarding_processes')
    op.drop_table('onboarding_processes')
    op.drop_table('engagements')
    op.drop_table('candidate_applications')
    op.drop_table('shift_swap_requests')
    op.drop_index(op.f('ix_payslips_person_id'), table_name='payslips')
    op.drop_table('payslips')
    op.drop_index(op.f('ix_onboarding_templates_tenant_id'), table_name='onboarding_templates')
    op.drop_table('onboarding_templates')
    op.drop_index(op.f('ix_hr_request_comments_hr_request_id'), table_name='hr_request_comments')
    op.drop_table('hr_request_comments')
    op.drop_index(op.f('ix_hr_policies_tenant_id'), table_name='hr_policies')
    op.drop_index(op.f('ix_hr_policies_policy_code'), table_name='hr_policies')
    op.drop_table('hr_policies')
    op.drop_index(op.f('ix_exit_settlements_exit_request_id'), table_name='exit_settlements')
    op.drop_table('exit_settlements')
    op.drop_index(op.f('ix_exit_interviews_exit_request_id'), table_name='exit_interviews')
    op.drop_table('exit_interviews')
    op.drop_index(op.f('ix_exit_handovers_exit_request_id'), table_name='exit_handovers')
    op.drop_table('exit_handovers')
    op.drop_index(op.f('ix_exit_clearance_tasks_exit_request_id'), table_name='exit_clearance_tasks')
    op.drop_table('exit_clearance_tasks')
    op.drop_index(op.f('ix_er_case_notes_tenant_id'), table_name='er_case_notes')
    op.drop_index(op.f('ix_er_case_notes_case_id'), table_name='er_case_notes')
    op.drop_table('er_case_notes')
    op.drop_index(op.f('ix_employment_history_tenant_id'), table_name='employment_history')
    op.drop_index(op.f('ix_employment_history_person_id'), table_name='employment_history')
    op.drop_table('employment_history')
    op.drop_index(op.f('ix_disciplinary_actions_tenant_id'), table_name='disciplinary_actions')
    op.drop_index(op.f('ix_disciplinary_actions_person_id'), table_name='disciplinary_actions')
    op.drop_index(op.f('ix_disciplinary_actions_case_id'), table_name='disciplinary_actions')
    op.drop_table('disciplinary_actions')
    op.drop_table('candidates')
    op.drop_table('workflow_instances')
    op.drop_table('training_certificates')
    op.drop_index(op.f('ix_shift_assignments_person_id'), table_name='shift_assignments')
    op.drop_table('shift_assignments')
    op.drop_index(op.f('ix_policy_acknowledgments_user_id'), table_name='policy_acknowledgments')
    op.drop_table('policy_acknowledgments')
    op.drop_index(op.f('ix_performance_reviews_person_id'), table_name='performance_reviews')
    op.drop_table('performance_reviews')
    op.drop_table('payroll_runs')
    op.drop_table('okr_key_results')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_locations_tenant_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_leave_requests_person_id'), table_name='leave_requests')
    op.drop_table('leave_requests')
    op.drop_table('job_openings')
    op.drop_index(op.f('ix_hr_requests_ticket_number'), table_name='hr_requests')
    op.drop_index(op.f('ix_hr_requests_tenant_id'), table_name='hr_requests')
    op.drop_index(op.f('ix_hr_requests_status'), table_name='hr_requests')
    op.drop_index(op.f('ix_hr_requests_requester_user_id'), table_name='hr_requests')
    op.drop_table('hr_requests')
    op.drop_table('grievance_cases')
    op.drop_index(op.f('ix_expense_claims_user_id'), table_name='expense_claims')
    op.drop_index(op.f('ix_expense_claims_ticket_number'), table_name='expense_claims')
    op.drop_index(op.f('ix_expense_claims_tenant_id'), table_name='expense_claims')
    op.drop_index(op.f('ix_expense_claims_person_id'), table_name='expense_claims')
    op.drop_table('expense_claims')
    op.drop_index(op.f('ix_exit_requests_user_id'), table_name='exit_requests')
    op.drop_index(op.f('ix_exit_requests_ticket_number'), table_name='exit_requests')
    op.drop_index(op.f('ix_exit_requests_tenant_id'), table_name='exit_requests')
    op.drop_index(op.f('ix_exit_requests_status'), table_name='exit_requests')
    op.drop_index(op.f('ix_exit_requests_person_id'), table_name='exit_requests')
    op.drop_table('exit_requests')
    op.drop_index(op.f('ix_employee_relations_cases_tenant_id'), table_name='employee_relations_cases')
    op.drop_index(op.f('ix_employee_relations_cases_subject_person_id'), table_name='employee_relations_cases')
    op.drop_index(op.f('ix_employee_relations_cases_case_number'), table_name='employee_relations_cases')
    op.drop_table('employee_relations_cases')
    op.drop_index(op.f('ix_employee_assets_user_id'), table_name='employee_assets')
    op.drop_index(op.f('ix_employee_assets_tenant_id'), table_name='employee_assets')
    op.drop_index(op.f('ix_employee_assets_person_id'), table_name='employee_assets')
    op.drop_index(op.f('ix_employee_assets_catalog_id'), table_name='employee_assets')
    op.drop_table('employee_assets')
    op.drop_table('documents')
    op.drop_index(op.f('ix_departments_tenant_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_cost_centers_tenant_id'), table_name='cost_centers')
    op.drop_table('cost_centers')
    op.drop_index(op.f('ix_compensation_revisions_tenant_id'), table_name='compensation_revisions')
    op.drop_index(op.f('ix_compensation_revisions_person_id'), table_name='compensation_revisions')
    op.drop_table('compensation_revisions')
    op.drop_index(op.f('ix_comp_off_requests_person_id'), table_name='comp_off_requests')
    op.drop_table('comp_off_requests')
    op.drop_index(op.f('ix_bonus_incentives_tenant_id'), table_name='bonus_incentives')
    op.drop_index(op.f('ix_bonus_incentives_person_id'), table_name='bonus_incentives')
    op.drop_table('bonus_incentives')
    op.drop_index(op.f('ix_benefit_enrollments_tenant_id'), table_name='benefit_enrollments')
    op.drop_index(op.f('ix_benefit_enrollments_person_id'), table_name='benefit_enrollments')
    op.drop_table('benefit_enrollments')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_attendance_person_id'), table_name='attendance')
    op.drop_table('attendance')
    op.drop_index(op.f('ix_asset_assignment_history_tenant_id'), table_name='asset_assignment_history')
    op.drop_index(op.f('ix_asset_assignment_history_employee_user_id'), table_name='asset_assignment_history')
    op.drop_index(op.f('ix_asset_assignment_history_employee_person_id'), table_name='asset_assignment_history')
    op.drop_index(op.f('ix_asset_assignment_history_asset_id'), table_name='asset_assignment_history')
    op.drop_table('asset_assignment_history')
    op.drop_table('announcements')
    op.drop_index(op.f('ix_active_sessions_user_id'), table_name='active_sessions')
    op.drop_index(op.f('ix_active_sessions_session_token_hash'), table_name='active_sessions')
    op.drop_table('active_sessions')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_salary_structures_person_id'), table_name='salary_structures')
    op.drop_table('salary_structures')
    op.drop_index(op.f('ix_okr_objectives_person_id'), table_name='okr_objectives')
    op.drop_table('okr_objectives')
    op.drop_index(op.f('ix_legal_entities_tenant_id'), table_name='legal_entities')
    op.drop_table('legal_entities')
    op.drop_index(op.f('ix_leave_balances_person_id'), table_name='leave_balances')
    op.drop_table('leave_balances')
    op.drop_table('holidays')
    op.drop_index(op.f('ix_enrollments_person_id'), table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index(op.f('ix_custom_field_values_entity_type'), table_name='custom_field_values')
    op.drop_index(op.f('ix_custom_field_values_entity_id'), table_name='custom_field_values')
    op.drop_table('custom_field_values')
    op.drop_index(op.f('ix_benefit_plans_tenant_id'), table_name='benefit_plans')
    op.drop_table('benefit_plans')
    op.drop_table('workflow_templates')
    op.drop_table('tenants')
    op.drop_table('shift_templates')
    op.drop_table('security_policies')
    op.drop_table('saml_providers')
    op.drop_table('review_cycles')
    op.drop_index(op.f('ix_persons_email'), table_name='persons')
    op.drop_table('persons')
    op.drop_table('payroll_components')
    op.drop_table('notification_templates')
    op.drop_table('leave_policies')
    op.drop_table('holiday_calendars')
    op.drop_index(op.f('ix_custom_field_definitions_entity_type'), table_name='custom_field_definitions')
    op.drop_table('custom_field_definitions')
    op.drop_table('currency_rates')
    op.drop_table('courses')
    op.drop_table('compliance_policies')
    op.drop_index(op.f('ix_asset_catalog_tenant_id'), table_name='asset_catalog')
    op.drop_table('asset_catalog')
    op.drop_index(op.f('ix_analytics_snapshots_metric_name'), table_name='analytics_snapshots')
    op.drop_table('analytics_snapshots')
    op.drop_table('ai_helpdesk_knowledge')
    op.drop_index(op.f('ix_ai_assessments_entity_type'), table_name='ai_assessments')
    op.drop_index(op.f('ix_ai_assessments_entity_id'), table_name='ai_assessments')
    op.drop_table('ai_assessments')
    # ### end Alembic commands ###
