from sqlalchemy import create_engine, text
from sqlalchemy.orm import sessionmaker

from app.config import settings

# Define roles and permissions as per PRD
ROLES = [
    "SUPER_ADMIN",
    "HR_ADMIN",
    "HIRING_MANAGER",
    "FINANCE",
    "EMPLOYEE",
]

PERMISSIONS = [
    "asset:view",
    "asset:manage",
    "asset:assign",
    "asset:transfer",
    "asset:return",
    "license:view",
    "license:manage",
    "license:assign",
    "license:revoke",
    "it_access:view",
    "it_access:manage",
    "it_access:approve",
    "it_access:provision",
    "it_access:revoke",
    "it_access:review",
    "workflow:view",
    "workflow:manage",
    "workflow:approve",
    "workflow:delegate",
    "workflow:escalate",
    "workflow:execute",
    "dashboard:view",
    "company_legal_profile:create",
    "company_legal_profile:view",
    "company_legal_profile:update",
    "company_legal_profile:delete",
    "statutory_registration:create",
    "statutory_registration:view",
    "statutory_registration:update",
    "statutory_registration:delete",
    "candidates:view",
    "candidates:create",
    "candidates:update",
    "candidates:select",
    "candidates:convert_to_trainee",
    "employees:view",
    "employees:view_own",
    "employees:create",
    "employees:update",
    "employees:delete",
    "trainees:view",
    "trainees:create",
    "trainees:update",
    "documents:view",
    "documents:view_own",
    "documents:upload",
    "documents:upload_own",
    "documents:update",
    "documents:verify",
    "documents:download",
    "documents:download_own",
    "documents:delete",
    "evaluations:view",
    "evaluations:view_own",
    "evaluations:create",
    "evaluations:update",
    "evaluations:submit",
    "stipends:view",
    "stipends:view_own",
    "stipends:create",
    "stipends:update",
    "stipends:approve",
    "attendance:view",
    "attendance:view_own",
    "attendance:create",
    "attendance:create_own",
    "attendance:update",
    "leave:view",
    "leave:view_own",
    "leave:create",
    "leave:create_own",
    "leave:approve",
    "templates:view",
    "templates:create",
    "templates:update",
    "templates:delete",
    "reports:view",
    "reports:export",
    "users:view",
    "users:create",
    "users:update",
    "users:delete",
    "roles:view",
    "roles:update",
    "audit:view",
    "shifts:view",
    "shifts:create",
    "shifts:update",
    "shifts:swap",
    "hr_requests:manage",
    "offboarding:manage",
    "compensation:view",
    "compensation:manage",
    "compensation:approve",
    "compensation:recommend",
    "hr_policy:view",
    "hr_policy:manage",
    "hr_policy:publish",
    "hr_policy:acknowledge",
    "employee_relations:view",
    "employee_relations:manage",
    "employee_relations:disciplinary",
    "compliance:view",
    "compliance:manage",
    "compliance:approve",
    "compliance:assign",
    "compliance:complete",
    "statutory:view",
    "statutory:manage",
    "statutory:calculate",
    "statutory:approve",
    "statutory_filing:view",
    "statutory_filing:manage",
    "statutory_filing:submit",
    "statutory_payment:view",
    "statutory_payment:manage",
    "tax:view",
    "tax:manage",
    "tax:declare",
    "analytics:view",
    "analytics:manage",
    "analytics:export",
    "analytics:schedule",
    "analytics:workforce",
    "analytics:attendance",
    "analytics:leave",
    "analytics:recruitment",
    "analytics:compensation",
    "analytics:payroll",
    "analytics:performance",
    "analytics:learning",
    "analytics:compliance",
    "dashboards:view",
    "dashboards:manage",
    "integrations:read",
    "integrations:view",
    "integrations:manage",
    "integrations:credentials:manage",
    "integrations:webhooks:manage",
    "integrations:api_keys:manage",
    "integrations:identity:manage",
    "integrations:scim:manage",
    "integrations:logs:read",
    "governance:read",
    "governance:view",
    "governance:manage",
    "governance:retention:manage",
    "governance:legal_hold:manage",
    "governance:privacy:manage",
    "governance:privacy:export",
    "governance:privacy:delete",
    "governance:backup:manage",
    "governance:dr:manage",
    "governance:bcp:manage",
    "governance:residency:manage",
    "finance:read",
    "finance:manage",
    "finance:cost_centers:manage",
    "finance:gl:manage",
    "finance:payroll_journal:manage",
    "finance:budget:manage",
    "finance:vendor:manage",
    "finance:invoice:manage",
    "finance:accounting_export",
    "finance:accrual:manage",
    "workforce_planning:read",
    "workforce_planning:manage",
    "workforce_planning:positions:manage",
    "workforce_planning:headcount:manage",
    "workforce_planning:skills:manage",
    "workforce_planning:succession:manage",
    "workforce_planning:talent:manage",
    "workforce_planning:scenarios:manage",
    "workforce_planning:hiring:manage",
    "workforce_planning:mobility:manage",
    "workforce_planning.read",
    "workforce_planning.manage",
    "workforce_planning.positions.manage",
    "workforce_planning.headcount.manage",
    "workforce_planning.skills.manage",
    "workforce_planning.succession.manage",
    "workforce_planning.talent.manage",
    "workforce_planning.scenarios.manage",
    "workforce_planning.hiring.manage",
    "workforce_planning.mobility.manage",
    "learning:read",
    "learning:manage",
    "learning:catalog:manage",
    "learning:enrollment:manage",
    "learning:assessment:manage",
    "learning:certification:manage",
    "learning:compliance:manage",
    "learning:development:manage",
    "learning:career:manage",
    "learning:mentoring:manage",
    "learning:analytics:read",
    "learning.read",
    "learning.manage",
    "learning.catalog.manage",
    "learning.enrollment.manage",
    "learning.assessment.manage",
    "learning.certification.manage",
    "learning.compliance.manage",
    "learning.development.manage",
    "learning.career.manage",
    "learning.mentoring.manage",
    "learning.analytics.read",
    "engagement:read",
    "engagement:manage",
    "engagement:surveys:manage",
    "engagement:responses:read",
    "engagement:analytics:read",
    "engagement:action_plans:manage",
    "engagement:feedback:manage",
    "engagement:suggestions:manage",
    "engagement:recognition:manage",
    "engagement:awards:manage",
    "engagement:culture:manage",
    "engagement.read",
    "engagement.manage",
    "engagement.surveys.manage",
    "engagement.responses.read",
    "engagement.analytics.read",
    "engagement.action_plans.manage",
    "engagement.feedback.manage",
    "engagement.suggestions.manage",
    "engagement.recognition.manage",
    "engagement.awards.manage",
    "engagement.culture.manage",
    "knowledge:read",
    "knowledge:manage",
    "knowledge:publish",
    "knowledge:review",
    "knowledge:analytics:read",
    "knowledge:feedback:manage",
    "knowledge.read",
    "knowledge.manage",
    "knowledge.publish",
    "knowledge.review",
    "knowledge.analytics.read",
    "knowledge.feedback.manage",
    "communications:read",
    "communications:manage",
    "communications:publish",
    "communications:acknowledgement:manage",
    "communications:analytics:read",
    "communications:templates:manage",
    "communications.read",
    "communications.manage",
    "communications.publish",
    "communications.acknowledgement.manage",
    "communications.analytics.read",
    "communications.templates.manage",
    "global_payroll:read",
    "global_payroll:manage",
    "global_payroll:configure",
    "global_payroll:process",
    "global_payroll:approve",
    "global_payroll:finalize",
    "global_payroll:adjust",
    "global_payroll:reconcile",
    "global_payroll:payslip:read",
    "global_payroll:provider:manage",
    "global_payroll:analytics:read",
    "global_payroll.read",
    "global_payroll.manage",
    "global_payroll.configure",
    "global_payroll.process",
    "global_payroll.approve",
    "global_payroll.finalize",
    "global_payroll.adjust",
    "global_payroll.reconcile",
    "global_payroll.payslip.read",
    "global_payroll.provider.manage",
    "global_payroll.analytics.read",
]

ROLE_PERMISSIONS = {
    "SUPER_ADMIN": PERMISSIONS,
    "HR_ADMIN": [
        "dashboard:view",
        "candidates:view",
        "candidates:create",
        "candidates:update",
        "candidates:select",
        "candidates:convert_to_trainee",
        "employees:view",
        "employees:view_own",
        "employees:create",
        "employees:update",
        "employees:delete",
        "trainees:view",
        "trainees:create",
        "trainees:update",
        "documents:view",
        "documents:view_own",
        "documents:upload",
        "documents:upload_own",
        "documents:update",
        "documents:verify",
        "documents:download",
        "documents:download_own",
        "documents:delete",
        "templates:view",
        "templates:create",
        "templates:update",
        "templates:delete",
        "reports:view",
        "reports:export",
        "audit:view",
        "attendance:view",
        "attendance:create",
        "attendance:update",
        "leave:view",
        "leave:create",
        "leave:approve",
        "evaluations:view",
        "evaluations:create",
        "evaluations:update",
        "evaluations:submit",
        "stipends:view",
        "stipends:create",
        "stipends:approve",
        "shifts:view",
        "shifts:create",
        "shifts:update",
        "shifts:swap",
        "hr_requests:manage",
        "offboarding:manage",
        "compensation:view",
        "compensation:manage",
        "compensation:approve",
        "hr_policy:view",
        "hr_policy:manage",
        "hr_policy:publish",
        "hr_policy:acknowledge",
        "employee_relations:view",
        "employee_relations:manage",
        "employee_relations:disciplinary",
        "compliance:view",
        "compliance:manage",
        "compliance:approve",
        "compliance:assign",
        "compliance:complete",
        "statutory:view",
        "statutory:manage",
        "statutory:approve",
        "statutory_filing:view",
        "statutory_filing:manage",
        "statutory_payment:view",
        "tax:view",
        "tax:manage",
        "analytics:view",
        "analytics:manage",
        "analytics:export",
        "analytics:schedule",
        "analytics:workforce",
        "analytics:attendance",
        "analytics:leave",
        "analytics:recruitment",
        "analytics:compensation",
        "analytics:performance",
        "analytics:learning",
        "analytics:compliance",
        "dashboards:view",
        "dashboards:manage",
        "integrations:read",
        "integrations:view",
        "integrations:manage",
        "integrations:credentials:manage",
        "integrations:webhooks:manage",
        "integrations:api_keys:manage",
        "integrations:identity:manage",
        "integrations:scim:manage",
        "integrations:logs:read",
        "governance:read",
        "governance:view",
        "governance:manage",
        "governance:retention:manage",
        "governance:legal_hold:manage",
        "governance:privacy:manage",
        "governance:privacy:export",
        "governance:privacy:delete",
        "governance:backup:manage",
        "governance:dr:manage",
        "governance:bcp:manage",
        "governance:residency:manage",
        "finance:read",
        "workforce_planning:read",
        "workforce_planning:manage",
        "workforce_planning:positions:manage",
        "workforce_planning:headcount:manage",
        "workforce_planning:skills:manage",
        "workforce_planning:succession:manage",
        "workforce_planning:talent:manage",
        "workforce_planning:scenarios:manage",
        "workforce_planning:hiring:manage",
        "workforce_planning:mobility:manage",
        "workforce_planning.read",
        "workforce_planning.manage",
        "learning:read",
        "learning:manage",
        "learning:catalog:manage",
        "learning:enrollment:manage",
        "learning:assessment:manage",
        "learning:certification:manage",
        "learning:compliance:manage",
        "learning:development:manage",
        "learning:career:manage",
        "learning:mentoring:manage",
        "learning:analytics:read",
        "learning.read",
        "learning.manage",
        "engagement:read",
        "engagement:manage",
        "engagement:surveys:manage",
        "engagement:responses:read",
        "engagement:analytics:read",
        "engagement:action_plans:manage",
        "engagement:feedback:manage",
        "engagement:suggestions:manage",
        "engagement:recognition:manage",
        "engagement:awards:manage",
        "engagement:culture:manage",
        "engagement.read",
        "engagement.manage",
        "knowledge:read",
        "knowledge:manage",
        "knowledge:publish",
        "knowledge:review",
        "knowledge:analytics:read",
        "knowledge:feedback:manage",
        "knowledge.read",
        "knowledge.manage",
        "knowledge.publish",
        "knowledge.review",
        "knowledge.analytics.read",
        "knowledge.feedback.manage",
        "communications:read",
        "communications:manage",
        "communications:publish",
        "communications:acknowledgement:manage",
        "communications:analytics:read",
        "communications:templates:manage",
        "communications.read",
        "communications.manage",
        "communications.publish",
        "communications.acknowledgement.manage",
        "communications.analytics.read",
        "communications.templates.manage",
        "global_payroll:read",
        "global_payroll:manage",
        "global_payroll:configure",
        "global_payroll:process",
        "global_payroll:approve",
        "global_payroll:finalize",
        "global_payroll:adjust",
        "global_payroll:reconcile",
        "global_payroll:payslip:read",
        "global_payroll:provider:manage",
        "global_payroll:analytics:read",
        "global_payroll.read",
        "global_payroll.manage",
        "global_payroll.configure",
        "global_payroll.process",
        "global_payroll.approve",
        "global_payroll.finalize",
        "global_payroll.adjust",
        "global_payroll.reconcile",
        "global_payroll.payslip.read",
        "global_payroll.provider.manage",
        "global_payroll.analytics.read",
    ],
    "HIRING_MANAGER": [
        "dashboard:view",
        "knowledge:read",
        "knowledge.read",
        "communications:read",
        "communications.read",
        "candidates:view",
        "candidates:create",
        "candidates:update",
        "candidates:select",
        "candidates:convert_to_trainee",
        "trainees:view",
        "trainees:create",
        "trainees:update",
        "evaluations:view",
        "evaluations:view_own",
        "evaluations:create",
        "evaluations:update",
        "evaluations:submit",
        "compensation:recommend",
        "hr_policy:view",
        "compliance:view",
        "analytics:view",
        "analytics:workforce",
        "analytics:attendance",
        "analytics:leave",
        "analytics:performance",
        "analytics:learning",
        "dashboards:view",
        "reports:view",
    ],
    "FINANCE": [
        "dashboard:view",
        "stipends:view",
        "stipends:view_own",
        "stipends:create",
        "stipends:update",
        "stipends:approve",
        "compensation:view",
        "hr_policy:view",
        "compliance:view",
        "statutory:view",
        "statutory:calculate",
        "statutory:approve",
        "statutory_filing:view",
        "statutory_filing:manage",
        "statutory_filing:submit",
        "statutory_payment:view",
        "statutory_payment:manage",
        "tax:view",
        "tax:manage",
        "analytics:view",
        "analytics:export",
        "analytics:compensation",
        "analytics:payroll",
        "analytics:compliance",
        "dashboards:view",
        "reports:view",
        "reports:export",
        "finance:read",
        "finance:manage",
        "finance:cost_centers:manage",
        "finance:gl:manage",
        "finance:payroll_journal:manage",
        "finance:budget:manage",
        "finance:vendor:manage",
        "finance:invoice:manage",
        "finance:accounting_export",
        "finance:accrual:manage",
        "global_payroll:read",
        "global_payroll:process",
        "global_payroll:reconcile",
        "global_payroll:analytics:read",
        "global_payroll.read",
        "global_payroll.process",
        "global_payroll.reconcile",
        "global_payroll.analytics.read",
    ],
    "EMPLOYEE": [
        "dashboard:view",
        "documents:view_own",
        "documents:download_own",
        "documents:upload_own",
        "attendance:view_own",
        "attendance:create_own",
        "leave:view_own",
        "leave:create_own",
        "employees:view_own",
        "hr_policy:view",
        "hr_policy:acknowledge",
        "tax:view",
        "tax:declare",
        "compliance:view",
        "analytics:view",
        "dashboards:view",
        "engagement:read",
        "engagement.read",
        "knowledge:read",
        "knowledge.read",
        "communications:read",
        "communications.read",
        "global_payroll:payslip:read",
        "global_payroll.payslip.read",
    ],
}

def main():
    import uuid
    import app.models  # noqa: F401
    from app.database import Base
    engine = create_engine(settings.database_url)
    Base.metadata.create_all(bind=engine)
    Session = sessionmaker(bind=engine)
    session = Session()

    # Insert roles with generated UUIDs if not existing
    for role_name in ROLES:
        role_id = str(uuid.uuid4())
        session.execute(
            text(
                "INSERT INTO roles (id, name) VALUES (:id, :name) ON CONFLICT (name) DO NOTHING"
            ),
            {"id": role_id, "name": role_name},
        )

    # Insert permissions with generated UUIDs if not existing
    for perm_code in PERMISSIONS:
        perm_id = str(uuid.uuid4())
        session.execute(
            text(
                "INSERT INTO permissions (id, code) VALUES (:id, :code) ON CONFLICT (code) DO NOTHING"
            ),
            {"id": perm_id, "code": perm_code},
        )

    # Build lookup maps for ids
    role_id_map = {row[1]: row[0] for row in session.execute(text("SELECT id, name FROM roles"))}
    perm_id_map = {row[1]: row[0] for row in session.execute(text("SELECT id, code FROM permissions"))}

    # Insert role_permission associations
    for role, perms in ROLE_PERMISSIONS.items():
        role_id = role_id_map.get(role)
        if not role_id:
            continue
        for perm in perms:
            perm_id = perm_id_map.get(perm)
            if not perm_id:
                continue
            session.execute(
                text(
                    "INSERT INTO role_permissions (role_id, permission_id) VALUES (:r, :p) ON CONFLICT (role_id, permission_id) DO NOTHING"
                ),
                {"r": role_id, "p": perm_id},
            )

    # Clean up stale role_permission associations that are no longer in
    # ROLE_PERMISSIONS (e.g. a permission was removed from a role).
    for role, perms in ROLE_PERMISSIONS.items():
        role_id = role_id_map.get(role)
        if not role_id:
            continue
        desired_perm_ids = [perm_id_map[p] for p in perms if p in perm_id_map]
        if desired_perm_ids:
            # Fetch current associations for this role
            current = session.execute(
                text("SELECT permission_id FROM role_permissions WHERE role_id = :r"),
                {"r": role_id},
            ).fetchall()
            for (pid,) in current:
                if pid not in desired_perm_ids:
                    session.execute(
                        text("DELETE FROM role_permissions WHERE role_id = :r AND permission_id = :p"),
                        {"r": role_id, "p": pid},
                    )
        else:
            session.execute(
                text("DELETE FROM role_permissions WHERE role_id = :r"),
                {"r": role_id},
            )

    session.commit()
    print("RBAC seed completed successfully.")

if __name__ == "__main__":
    main()
